### ISSUE TITLE
Cannot find a property by the key: GenerateColumnsBeforeRepaint

### ISSUE THREAD

**Issue by ghost** [Acumatica/Acumatica-LotSerialNbrAttribute#1]
On 18.101.039 with Manufacturing customization, I get the following message when I attempt to import the customization. I've unpublished all customizations and also tried importing to a stripped down installation with the same result.

> Error during file upload: An error on the page ~/pages/so/so301000.aspx with the message: Cannot find a property by the key: GenerateColumnsBeforeRepaint for PX.Web.UI.PXGrid

**Comment by DhirenChhapgar** [comment]
Thank you for bringing this to our attention.

_GenerateColumnsBeforeRepaint_ Property is introduced in **18.102.0048** build for **2018R1** series. Please upgrade your environment to 18.102.0048 build or higher. We have updated prerequisites for **2018R1** series in ReadMe.
