### ISSUE TITLE
Unable to publish latest version with 2018 R2 manufacturing.

### ISSUE THREAD

**Issue by sprangerd** [Acumatica/Acumatica-LotSerialNbrAttribute#4]
Acumatica 18.204.0013
Manufacturing.18.203.0006.15
ManufacturingWIKI.18.203.0006.15

publish will not validate 
Publish Customization
Compiled projects: Manufacturing,PXLotSertialNbrAttributeExtPkg
Conflict control ID:phDS_ds from page ~/pages/so/so301000.aspx
Validation failed.

I am not interested in adding support or functionality to manufacturing extension. I have need to capture some attributes on receiving lot #'s only.

can PXLotSerialNbrAttributeExtPkg be updated to at least publish with Manufacturing.18.203.0006.15

Don

**Comment by DhirenChhapgar** [comment]
To resolve such error/s, you need to specify Level for customization projects.

![image](https://user-images.githubusercontent.com/5994708/49692611-c78f7300-fb2c-11e8-9e63-daaf2eacd896.png)

**Comment by PaulHec** [comment]
Hi Dhiren
Do you perhaps have an upgraded PXLotSertialNbrAttributeExtPkg customization that works on 2019 R2.
If you do please send me a link where I can download it.
Kind Regards

**Comment by DhirenChhapgar** [comment]
You should be able to use package available for [2019R1 series](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute/releases)

**Comment by PaulHec** [comment]
Thank you Dhiren
It is working perfectly.
