### ISSUE TITLE
Fails to Compile in 19R1

### ISSUE THREAD

**Issue by zorho** [Acumatica/Acumatica-LotSerialNbrAttribute#5]
Worked fine in our 17R2 environment. Currently, we only have JAMS installed.
Thanks!

**Comment by zorho** [comment]
Build 19.105.0032

**Comment by DhirenChhapgar** [comment]
You need to download appropriate Acumatica version specific deployment package from [releases tab](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute/releases).

**Comment by zorho** [comment]
Thanks for the quick reply. That did it.
