### ISSUE TITLE
We love this customization but we have an issue

### ISSUE THREAD

**Issue by mcoman** [Acumatica/Acumatica-LotSerialNbrAttribute#7]
The screen disappeared from the menu in 2019r1.  We republished the customization with no luck.  All the tables are still there we just cant get the screen backup on the profiles menu.  Is there something we did wrong or can fix?

**Comment by DhirenChhapgar** [comment]
@mcoman  which screen is disappeared ?

**Comment by mcoman** [comment]
Dhiren,

The profile in202501 screen.  It was on the inventory screen, Profiles sections.  And I can seem to find it on the Edit menu items either.

**Comment by mcoman** [comment]
I would really like to show you the problem sometime.

**Comment by mcoman** [comment]
Dhiren,

I made the mistake of not checking access rights by screen.  Thank you for writing this screen our customer loves it.

**Comment by DhirenChhapgar** [comment]
@mcoman Thank you for confirming
