### ISSUE TITLE
Acumatica Manufacturing 2020R1 conflicts with this customization 

### ISSUE THREAD

**Issue by PJvGinkel** [Acumatica/Acumatica-LotSerialNbrAttribute#8]
Hi,
I published the manufacturing edition of Acumatica, and when publishing this Lot/Serial Attribute customization it unpublishes the manufacturing feature. When I try to publish both, I get an error:
"
Compiled projects: Manufacturing.20.104.0012.31,PXLotSertialNbrAttributeExtPkg1
Conflict control ID:phDS_ds from page ~/pages/so/so301000.aspx
"

Is there a workaround for this?

**Comment by DhirenChhapgar** [comment]
To resolve such error/s, you need to specify Level for customization projects.

![image](https://user-images.githubusercontent.com/5994708/86680564-b3437e80-bfcc-11ea-8ec9-7295582f8584.png)
